/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitness;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.Random;
/**
 *
 * @author Ashish Panda
 */
public class Loginform extends javax.swing.JFrame {

    /**
     * Creates new form Loginform
     */
    public Loginform() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();

        jFrame1.setMinimumSize(new java.awt.Dimension(1440, 900));
        jFrame1.getContentPane().setLayout(null);

        jLabel6.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 90, 270, 60);

        jLabel7.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Password");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(280, 140, 240, 30);

        jLabel8.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CONFIRM PASSWORD");
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(280, 180, 320, 30);

        jTextField2.setFont(new java.awt.Font("Algerian", 1, 18));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField2);
        jTextField2.setBounds(640, 100, 220, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18));
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(660, 430, 220, 40);

        jLabel9.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CAPTCHA");
        jFrame1.getContentPane().add(jLabel9);
        jLabel9.setBounds(390, 450, 170, 50);

        jButton3.setFont(new java.awt.Font("Algerian", 1, 18));
        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(540, 570, 140, 33);

        jButton4.setFont(new java.awt.Font("Algerian", 1, 18));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Back");
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton4);
        jButton4.setBounds(10, 10, 110, 33);

        jButton5.setFont(new java.awt.Font("Algerian", 1, 18));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(600, 470, 60, 40);

        jTextField5.setFont(new java.awt.Font("Arial", 1, 18));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField5);
        jTextField5.setBounds(660, 470, 220, 40);

        jLabel11.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("current weight");
        jFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(280, 340, 190, 30);

        jLabel13.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Dob");
        jFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(280, 300, 110, 30);

        jLabel12.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Height");
        jFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(280, 260, 80, 30);

        jLabel14.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("place");
        jFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(280, 220, 290, 30);

        jTextField6.setFont(new java.awt.Font("Algerian", 1, 18));
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField6);
        jTextField6.setBounds(640, 300, 220, 30);

        jTextField8.setFont(new java.awt.Font("Algerian", 1, 18));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField8);
        jTextField8.setBounds(640, 260, 220, 30);

        jTextField9.setFont(new java.awt.Font("Algerian", 1, 18));
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField9);
        jTextField9.setBounds(640, 340, 220, 30);

        jTextField10.setFont(new java.awt.Font("Algerian", 1, 18));
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jTextField10);
        jTextField10.setBounds(640, 220, 220, 30);
        jFrame1.getContentPane().add(jPasswordField3);
        jPasswordField3.setBounds(640, 180, 220, 30);
        jFrame1.getContentPane().add(jPasswordField2);
        jPasswordField2.setBounds(640, 140, 220, 30);

        jLabel5.setFont(new java.awt.Font("Algerian", 1, 18));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(-10, -160, 1590, 1190);

        jCheckBox1.setText("jCheckBox1");
        jFrame1.getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(600, 520, 81, 23);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Veal Nerve", 0, 48));
        jLabel1.setText("NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(420, 200, 180, 50);

        jLabel2.setFont(new java.awt.Font("Veal Nerve", 0, 48));
        jLabel2.setText("PASSWORD");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 300, 290, 43);

        jTextField1.setFont(new java.awt.Font("Veal Nerve", 0, 36));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(630, 200, 300, 50);

        jLabel3.setFont(new java.awt.Font("Veal Nerve", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("New Here?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(540, 520, 100, 30);

        jPasswordField1.setFont(new java.awt.Font("Veal Nerve", 0, 36));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(630, 300, 300, 50);

        jButton1.setFont(new java.awt.Font("Veal Nerve", 0, 18));
        jButton1.setText("SIGN IN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 520, 120, 33);

        jButton2.setFont(new java.awt.Font("Veal Nerve", 0, 36));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(630, 410, 170, 40);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1440, 900);
        getContentPane().add(jOptionPane1);
        jOptionPane1.setBounds(50, 300, 262, 90);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(true);
       Random a=new Random();
        int b=a.nextInt((10-1+1))+1;
         int c=a.nextInt((10-1+1))+1;
          int d=a.nextInt((10-1+1))+1;
       {jLabel10.setText(""+b+c+d);}

    }//GEN-LAST:event_jButton1ActionPerformed
Connection con=null;
Statement stmt=null;
ResultSet rs=null;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        try
        {Class.forName("java.sql.Driver");
        con=DriverManager.getConnection("jdbc:mysql://localhost/Project","root","tiger");
        stmt=con.createStatement();
       String query="select * from id where name='"+jTextField1.getText()+"';";
       rs=stmt.executeQuery(query);
        if(rs.next())
        { //char a=jPasswordField1.getPassword();
         String Name=rs.getString("Name");
         String Password=rs.getString("Password");
         if (Password.equals(Password)==true)
         {jOptionPane1.showMessageDialog(null,"hello user"+" "+jTextField1.getText());}
         else
         {jOptionPane1.showMessageDialog(null,"plz check ur password or username");}

        }
        else
        {jOptionPane1.showMessageDialog(null,"Plz checkid and password");
        }}

        catch (Exception e)
        {e.printStackTrace();
        jOptionPane1.showMessageDialog(null,"error");}
        String z=jTextField1.getText();


        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Random a=new Random();
        int b=a.nextInt((10-1+1))+1;
        int c=a.nextInt((10-1+1))+1;
        int d=a.nextInt((10-1+1))+1;
        {jLabel10.setText(""+b+c+d);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jFrame1.dispose();
}//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        String x=new String(jPasswordField3.getPassword());
        String y=new String(jPasswordField2.getPassword());
        int w=Integer.parseInt(jLabel10.getText());
        int v=Integer.parseInt(jTextField5.getText());
        int ans = jOptionPane1.showConfirmDialog(null, "WANT TO CREATE ACCOUNT?");
        if (ans==jOptionPane1.YES_OPTION) {
            try {
                Class.forName("java.sql.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost/id","root","tiger");
                stmt=con.createStatement();
                if(x.equals(y)) {
                    if(w==v) {
                        String query="insert into fitness values('"+jTextField2.getText()+"','"+new String(jPasswordField2.getPassword())+"','"+jTextField10.getText()+"','"+jTextField8.getText()+"','"+jTextField6.getText()+"','"+jTextField9.getText()+"');";
                        System.out.print(query);
                        stmt.executeUpdate(query);
                        jOptionPane1.showMessageDialog(null,"Account Created.");} else {
                        jOptionPane1.showMessageDialog(null,"check Capture");}
                }} catch(Exception e) {
                    e.printStackTrace();
                    jOptionPane1.showMessageDialog(null,"error in insertion");
                }}
        {
            jTextField1.setText("");
            jTextField2.setText("");

        }



    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextField2ActionPerformed
 Random a=new Random();
        int b=a.nextInt((10-1+1))+1;
         int c=a.nextInt((10-1+1))+1;
          int d=a.nextInt((10-1+1))+1;


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
